/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: "var(--font-inter)",
        satoshi: "var(--font-satoshi)",
        geistSans: "var(--font-geist-sans)",
        geistMono: "var(--font-geist-mono)",
        nunito: "var(--font-nunito)",
        switzer: "var(--font-switzer)",
        robotoSerif: "var(--font-roboto-serif)",
        playfairDisplay: "var(--font-playfair-display)",
      },
      backgroundImage: {
        texture: "url('/images/texture.webp')",
        homeGradient:
          "linear-gradient(90deg, rgb(114, 84, 63) 0%, rgb(243, 215, 198) 75.52%)",
      },
      backgroundColor: {
        theme: "#86644C",
        themeLight: "#3e342c",
        themeDark: "#322a23",
        themeBlue: "#12466F",
        themeGray: "#FAFAFA",
        themeGray2: "#F8F8F8",
        themeGray3: "#EBEBEB",
        homeCards: "#FFFFFFBF",
        themePink: "#EEC1FD",
        themeSkyBlue: "#ADEEF5",
        themeYellow: "#FADD81",
        themeLightGreen: "#21965314",
        emailHeader: "#5b6777",
        emailBody: "#f8f9fc",
        borderColor: "#E2E8F0",
        themeTab: "#F7F9FC",
        tabBorderColor: "#DDDDDDDD",
        buttonBorderColor: "#D0D5DD",
        profilePhoto: "#D9D9D9",
        dottedLine: "#22151866",
        themeYellowLight: "#FDE24F",
        themeYellowDark: "#E9C607",
        headerColor: "#645548",
        cardBorderColor: "#FFF3DDCC",
      },
      colors: {
        theme: "#86644C",
        themeLight: "#3e342c",
        themeDark: "#322a23",
        labelColor: "#212B36",
        inputBorder: "#00000033",
        themeLightGray: "#8F95B2",
        themeGreen: "#219653",
        secondary: "#64748B",
        dark: "#1E293B",
        tabColor: "#12466F1A",
        emailHeader: "#5b6777",
        emailBody: "#f8f9fc",
        borderColor: "#E2E8F0",
        tabBorderColor: "#DDDDDDDD",
        buttonTextColor: "#EFF4FB",
        buttonBorderColor: "#D0D5DD",
        themeYellowLight: "#FDE24F",
        themeYellowDark: "#E9C607",
        quantityBtn: "#F8E4BECC",
        cardBorderColor: "#FFF3DDCC",
      },
      boxShadow: {
        textShadow:
          "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
        tabShadow: " 0px 0px 2px 0px #0000001F",
        tableShadow: "0px 8px 13px -3px #00000012",
        buttonShadow: "0px 1px 2px 0px #1018280D",
        customYellow: "0 0px 6px rgba(248, 228, 190, 0.5)",
      },
    },
  },
  plugins: [],
};
